UPDATE: populate gum log

diff --git a/bin/pkgadd b/bin/pkgadd
--- a/bin/pkgadd
+++ b/bin/pkgadd
@@ -6,7 +6,7 @@ fi
 
 for pkg in "$@"; do
   if ! pacman -Q "$pkg" &>/dev/null; then
-    echo -e "\033[31mError: Package '$pkg' did not installed\033[0m" >&2
+    gum log --level error "Error: Package '$pkg' did not installed" >&2
     exit 1
   fi
 done
