UPDATE: scripts, and add Omarchy repo

diff --git a/scripts/.config/scripts/pkg-missing b/scripts/.config/scripts/pkg-missing
--- a/scripts/.config/scripts/pkg-missing
+++ b/scripts/.config/scripts/pkg-missing
@@ -2,8 +2,9 @@
 
 # Returns true if any of the commands passed in as arguments are missing on the system.
 
-for cmd in "$@"; do
-  if ! command -v "$cmd" &>/dev/null; then
+for pkg in "$@"; do
+  if ! pacman -Q "$pkg" &>/dev/null; then
+    echo "$pkg is missing..."
     exit 0
   fi
 done
diff --git a/scripts/.config/scripts/pkgadd b/scripts/.config/scripts/pkgadd
--- a/scripts/.config/scripts/pkgadd
+++ b/scripts/.config/scripts/pkgadd
@@ -1,6 +1,14 @@
 #!/bin/bash
 
-cmd="$*"
-sudo -v
-yay -S --noconfirm --needed $cmd
-sudo updatedb
+if pkg-missing "$@"; then
+  yay -S --noconfirm --needed "$@" || exit 1
+fi
+
+for pkg in "$@"; do
+  if ! pacman -Q "$pkg" &>/dev/null; then
+    echo -e "\033[31mError: Package '$pkg' did not install\033[0m" >&2
+    exit 1
+  fi
+done
+
+exit 0
